# General constants
SCREEN_WIDTH = 900
SCREEN_HEIGHT = 480
TITLE = "Number Crunch"
GRID_WIDTH = 3
GRID_HEIGHT = 3

# Rectangle sizes
BUTTON_WIDTH = 100
BUTTON_HEIGHT = 50
SQUARE_SIZE = 95
GRID_GAP = 5
SHOP_WIDTH = 340
SHOP_HEIGHT = 50

# Text sizes
TITLE_SIZE = 72
SMALL_TITLE_SIZE = 36
NUMBER_SIZE = 36
COST_SIZE = 30
STATE_SIZE = 30

# Element positions
GRID_X = 30
STATE_X_1 = GRID_X
STATE_X_2 = 230
SHOP_X = 430
